# coding=utf-8
from typing import Dict, List


class SampleLangPhrases:

    langs: Dict[str, List[str]] = {
        'af': ['Afrikaans', 'Afrikaans'],
        'ar': ['Arabic', 'العَرَبِيَّ', 'al\'Arabiyyeẗ'],
        'bg': ['Bulgarian', 'български език bălgarski ezik'],
        'bn': ['Bengali', 'বাংলা Bāŋlā'],
        'bs': ['Bosnian', 'bosanski'],
        'ca': ['Catalan; Valencian', 'català, valencià'],
        'cs': ['Czech', 'čeština; český jazyk'],
        'da': ['Danish', 'dansk'],
        'de': ['German', 'Deutsch'],
        'el': ['Greek', 'Νέα Ελληνικά Néa Ellêniká'],
        'en': ['English', 'English'],
        'et': ['Estonian', 'eesti keel'],
        'es': ['Spanish; Castilian', 'español; castellano'],
        'fi': ['Finnish', 'suomen kieli'],
        'fr': ['French', 'français'],
        'gu': ['Gujarati', 'ગુજરાતી Gujarātī'],
        'iw': ['Hebrew', "עברית 'Ivriyþ"],
        'hi': ['Hindi', 'हिन्दी Hindī'],
        'hr': ['Croatian', 'hrvatski'],
        'hu': ['Hungarian', 'magyar nyelv'],
        'id': ['Indonesian', 'bahasa Indonesia'],
        'is': ['Icelandic', 'íslenska'],
        'it': ['Italian', 'taliano; lingua italiana'],
        'ja': ['Japanese', '日本語 Nihongo'],
        'jw': ['Javanese', 'ꦧꦱꦗꦮ / Basa Jawa'],
        'km': ['Khmer', 'ភាសាខ្មែរ Phiəsaakhmær'],
        'kn': ['Kannada', 'ಕನ್ನಡ Kannađa'],
        'ko': ['Korean', "한국어 Han'gug'ô"],
        'la': ['Latin', 'No Sample'],
        'lv': ['Latvian', 'Latviešu valoda'],
        'ml': ['Malayalam', 'മലയാളം  Malayāļã'],
        'mr': ['Marathi', 'मराठी Marāţhī'],
        'ms': ['Malay', 'Bahasa Melayu'],
        'my': ['Myanmar (Burmese)', 'မြန်မာစာ Mrãmācā; မြန်မာစကား Mrãmākā: | Myanmar'],
        'ne': ['Nepali', 'नेपाली भाषा Nepālī bhāśā'],
        'nl': ['Dutch; Flemish', 'Dutch; Flemish'],
        'no': ['Norwegian', 'norsk nynorsk'],
        'pl': ['Polish', 'Język polski'],
        'pt': ['Portuguese', 'português'],
        'ro': ['Romanian', 'limba română'],
        'ru': ['Russian', 'русский язык russkiĭ âzık'],
        'si': ['Sinhala', 'සිංහල Sĩhala'],
        'sk': ['Slovak', 'slovenčina; slovenský jazyk'],
        'sq': ['Albanian', 'Shqip'],
        'sr': ['Serbian', 'српски / srpski'],
        'su': ['Sundanese', 'ᮘᮞ ᮞᮥᮔ᮪ᮓ / Basa Sunda'],
        'sv': ['Swedish', 'svenska'],
        'sw': ['Swahili', 'Kiswahili'],
        'ta': ['Tamil', 'தமிழ் Tamił'],
        'te': ['Telugu', 'తెలుగు Telugu'],
        'th': ['Thai', 'ภาษาไทย Phasathay'],
        'tl': ['Filipino; Pilipino', 'Wikang, Filipino'],
        'tr': ['Turkish', 'Türkçe'],
        'uk': ['Ukrainian', 'Українська мова; Українська'],
        'ur': ['Urdu', 'و Urduw'],
        'vi': ['Vietnamese', 'Tiếng Việt'],
        #  'zh-CN': ['Chinese (Simplified)',
        #  'zh-TW': ['Chinese (Mandarin/Taiwan)'],
        'zh': ['Chinese (Mandarin)', '中文 Zhōngwén; 汉语; 漢語 Hànyǔ']
    }
