# coding=utf-8

from common import *


class GoogleData:
    """
    Contains long, boring tables for looking up possibly supported languages,
    country codes and the appropriate Google Domain

    See the gtts documentation for more info.

    There are two tables defined here:
        country_code_country_tld and lang_variants

    Together you can determine which 'top-level domain' to use for a given
    language variant and what language and country codes to use.

    Note that Google does not provide much information about this and that
    there are likely invalid or language, country and code combinations returned
    here. This is experimental. The gtts package does return known working information,
    but is known to be incomplete.
    """

    """
        The country_code_country_tld table takes an ISO3166-1 two-letter 
        country code and returns a Tuple[<google_tld>, <country_name]
        
        Where <google_tld> is the 'top-level-domain' that google should use
        to get the (hopefully) appropriate accent(s) for languages supported
        for the country.
        
        The <country_name> is an English description of the country. 
    """
    country_code_country_tld: Dict[str, Tuple[str, str]] = {
        #                          ISO3166-1, <google tld>, <country name>
        "ad": ("ad", "Andorra"),
        "ae": ("ae", "United Arab Emirates (the)"),
        "af": ("com.af", "Afghanistan"),
        "ag": ("com.ag", "Antigua and Barbuda"),
        "ai": (None, "Anguilla"),
        "al": ("al", "Albania"),
        "am": ("am", "Armenia"),
        "ao": ("co.ao", "Angola"),
        "aq": (None, "Antarctica"),
        "ar": ("com.ar", "Argentina"),
        "as": ("as", "American Samoa"),
        "at": ("at", "Austria"),
        "au": ("com.au", "Australia"),
        "aw": (None, "Aruba"),
        "ax": (None, "Åland Islands"),
        "az": ("az", "Azerbaijan"),
        "ba": ("ba", "Bosnia and Herzegovina"),
        "bb": (None, "Barbados"),
        "bd": ("com.bd", "Bangladesh"),
        "be": ("be", "Belgium"),
        "bf": ("bf", "Burkina Faso"),
        "bg": ("bg", "Bulgaria"),
        "bh": ("com.bh", "Bahrain"),
        "bi": ("bi", "Burundi"),
        "bj": ("bj", "Benin"),
        "bl": (None, "Saint Barthélemy"),
        "bm": (None, "Bermuda"),
        "bn": ("com.bn", "Brunei Darussalam"),
        "bo": ("com.bo", "Bolivia (Plurinational State of)"),
        "bq": (None, "Bonaire, Sint Eustatius and Saba"),
        "br": ("com.br", "Brazil"),
        "bs": ("bs", "Bahamas (the)"),
        "bt": ("bt", "Bhutan"),
        "bv": (None, "Bouvet Island"),
        "bw": ("co.bw", "Botswana"),
        "by": ("by", "Belarus"),
        "bz": ("com.bz", "Belize"),
        "ca": ("ca", "Canada"),
        "cc": (None, "Cocos (Keeling) Islands (the)"),
        "cd": ("cd", "Congo (the Democratic Republic of the)"),
        "cf": ("cf", "Central African Republic (the)"),
        "cg": ("cg", "Congo (the)"),
        "ch": ("ch", "Switzerland"),
        "ci": ("ci", "Côte d'Ivoire"),
        "ck": ("co.ck", "Cook Islands (the)"),
        "cl": ("cl", "Chile"),
        "cm": ("cm", "Cameroon"),
        "cn": ("cn", "China"),
        "co": ("com.co", "Colombia"),
        "cr": ("co.cr", "Costa Rica"),
        "cu": ("com.cu", "Cuba"),
        "cv": ("cv", "Cabo Verde"),
        "cw": (None, "Curaçao"),
        "cx": (None, "Christmas Island"),
        "cy": ("com.cy", "Cyprus"),
        "cz": ("cz", "Czechia"),
        "de": ("de", "Germany"),
        "dj": ("dj", "Djibouti"),
        "dk": ("dk", "Denmark"),
        "dm": ("dm", "Dominica"),
        "do": ("com.do", "Dominican Republic (the)"),
        "dz": ("dz", "Algeria"),
        "ec": ("com.ec", "Ecuador"),
        "ee": ("ee", "Estonia"),
        "eg": ("com.eg", "Egypt"),
        "eh": (None, "Western Sahara"),
        "en": ('com', 'English'),
        "er": (None, "Eritrea"),
        "es": ("es", "Spain"),
        "et": ("com.et", "Ethiopia"),
        "fi": ("fi", "Finland"),
        "fj": ("com.fj", "Fiji"),
        "fk": ("Falkland Islands (the) [Malvinas]"),
        "fm": ("fm", "Micronesia (Federated States of)"),
        "fo": ("Faroe Islands (the)"),
        "fr": ("fr", "France"),
        "ga": ("ga", "Gabon"),
        "gb": ("co.uk", "United Kingdom of Great Britain and Northern Ireland (the)"),
        "gd": (None, "Grenada"),
        "ge": ("ge", "Georgia"),
        "gf": (None, "French Guiana"),
        "gg": ("gg", "Guernsey"),
        "gh": ("com.gh", "Ghana"),
        "gi": ("com.gi", "Gibraltar"),
        "gl": ("gl", "Greenland"),
        "gm": ("gm", "Gambia (the)"),
        "gn": (None, "Guinea"),
        "gp": (None, "Guadeloupe"),
        "gq": (None, "Equatorial Guinea"),
        "gr": ("gr", "Greece"),
        "gs": ("South Georgia and the South Sandwich Islands"),
        "gt": ("com.gt", "Guatemala"),
        "gu": (None, "Guam"),
        "gw": (None, "Guinea-Bissau"),
        "gy": ("gy", "Guyana"),
        "hk": ("com.hk", "Hong Kong"),
        "hm": (None, "Heard Island and McDonald Islands"),
        "hn": ("hn", "Honduras"),
        "hr": ("hr", "Croatia"),
        "ht": ("ht", "Haiti"),
        "hu": ("hu", "Hungary"),
        "id": ("co.id", "Indonesia"),
        "ie": ("ie", "Ireland"),
        "il": ("co.il", "Israel"),
        "im": ("im", "Isle of Man"),
        "in": ("co.in", "India"),
        "io": (None, "British Indian Ocean Territory (the)"),
        "iq": ("iq", "Iraq"),
        "ir": ("Iran (Islamic Republic of)"),
        "is": ("is", "Iceland"),
        "it": ("it", "Italy"),
        "je": ("je", "Jersey"),
        "jm": ("com.jm", "Jamaica"),
        "jo": ("jo", "Jordan"),
        "jp": ("co.jp", "Japan"),
        "ke": ("co.ke", "Kenya"),
        "kg": ("kg", "Kyrgyzstan"),
        "kh": ("com.kh", "Cambodia"),
        "ki": ("ki", "Kiribati"),
        "km": (None, "Comoros (the)"),
        "kn": (None, "Saint Kitts and Nevis"),
        "kp": (None, "Korea (the Democratic People's Republic of)"),
        "kr": ("co.kr", "Korea (the Republic of)"),
        "kw": ("com.kw", "Kuwait"),
        "ky": (None, "Cayman Islands (the)"),
        "kz": ("kz", "Kazakhstan"),
        "la": ("la", "Lao People's Democratic Republic (the)"),
        "lb": ("com.lb", "Lebanon"),
        "lc": (None, "Saint Lucia"),
        "li": ("li", "Liechtenstein"),
        "lk": ("lk", "Sri Lanka"),
        "lr": (None, "Liberia"),
        "ls": ("co.ls", "Lesotho"),
        "lt": ("lt", "Lithuania"),
        "lu": ("lu", "Luxembourg"),
        "lv": ("lv", "Latvia"),
        "ly": ("com.ly", "Libya"),
        "ma": ("co.ma", "Morocco"),
        "mc": (None, "Monaco"),
        "md": ("md", "Moldova (the Republic of)"),
        "me": ("me", "Montenegro"),
        "mf": (None, "Saint Martin (French part)"),
        "mg": ("mg", "Madagascar"),
        "mh": (None, "Marshall Islands (the)"),
        "mk": ("mk", "Republic of North Macedonia"),
        "ml": ("ml", "Mali"),
        "mm": ("com.mm", "Myanmar"),
        "mn": ("mn", "Mongolia"),
        "mo": (None, "Macao"),
        "mp": (None, "Northern Mariana Islands (the)"),
        "mq": (None, "Martinique"),
        "mr": (None, "Mauritania"),
        "ms": (None, "Montserrat"),
        "mt": ("com.mt", "Malta"),
        "mu": ("mu", "Mauritius"),
        "mv": ("mv", "Maldives"),
        "mw": ("mw", "Malawi"),
        "mx": ("com.mx", "Mexico"),
        "my": ("com.my", "Malaysia"),
        "mz": ("co.mz", "Mozambique"),
        "na": ("com.na", "Namibia"),
        "nc": (None, "New Caledonia"),
        "ne": ("ne", "Niger (the)"),
        "nf": (None, "Norfolk Island"),
        "ng": ("com.ng", "Nigeria"),
        "ni": ("com.ni", "Nicaragua"),
        "nl": ("nl", "Netherlands (the)"),
        "no": ("no", "Norway"),
        "np": ("com.np", "Nepal"),
        "nr": ("nr", "Nauru"),
        "nu": ("nu", "Niue"),
        "nz": ("co.nz", "New Zealand"),
        "om": ("com.om", "Oman"),
        "pa": ("com.pa", "Panama"),
        "pe": ("com.pe", "Peru"),
        "pf": (None, "French Polynesia"),
        "pg": ("com.pg", "Papua New Guinea"),
        "ph": ("com.ph", "Philippines (the)"),
        "pk": ("com.pk", "Pakistan"),
        "pl": ("pl", "Poland"),
        "pm": (None, "Saint Pierre and Miquelon"),
        "pn": ("pn", "Pitcairn"),
        "pr": ("com.pr", "Puerto Rico"),
        "ps": ("ps", "Palestine, State of"),
        "pt": ("pt", "Portugal"),
        "pw": (None, "Palau"),
        "py": ("com.py", "Paraguay"),
        "qa": ("com.qa", "Qatar"),
        "re": (None, "Réunion"),
        "ro": ("ro", "Romania"),
        "rs": ("rs", "Serbia"),
        "ru": ("ru", "Russian Federation (the)"),
        "rw": ("rw", "Rwanda"),
        "sa": ("com.sa", "Saudi Arabia"),
        "sb": ("com.sb", "Solomon Islands"),
        "sc": ("sc", "Seychelles"),
        "sd": (None, "Sudan (the)"),
        "se": ("se", "Sweden"),
        "sg": ("com.sg", "Singapore"),
        "sh": ("sh", "Saint Helena, Ascension and Tristan da Cunha"),
        "si": ("si", "Slovenia"),
        "sj": (None, "Svalbard and Jan Mayen"),
        "sk": ("sk", "Slovakia"),
        "sl": ("com.sl", "Sierra Leone"),
        "sm": ("sm", "San Marino"),
        "sn": ("sn", "Senegal"),
        "so": ("so", "Somalia"),
        "sr": ("sr", "Suriname"),
        "ss": (None, "South Sudan"),
        "st": ("st", "Sao Tome and Principe"),
        "sv": ("com.sv", "El Salvador"),
        "sx": (None, "Sint Maarten (Dutch part)"),
        "sy": (None, "Syrian Arab Republic"),
        "sz": (None, "Eswatini"),
        "tc": (None, "Turks and Caicos Islands (the)"),
        "td": ("td", "Chad"),
        "tf": (None, "French Southern Territories (the)"),
        "tg": ("tg", "Togo"),
        "th": ("co.th", "Thailand"),
        "tj": ("com.tj", "Tajikistan"),
        "tk": (None, "Tokelau"),
        "tl": ("tl", "Timor-Leste"),
        "tm": ("tm", "Turkmenistan"),
        "tn": ("tn", "Tunisia"),
        "to": ("to", "Tonga"),
        "tr": ("com.tr", "Turkey"),
        "tt": ("tt", "Trinidad and Tobago"),
        "tv": (None, "Tuvalu"),
        "tw": ("com.tw", "Taiwan (Province of China)"),
        "tz": ("co.tz", "Tanzania, United Republic of"),
        "ua": ("com.ua", "Ukraine"),
        "ug": ("co.ug", "Uganda"),
        "um": (None, "United States Minor Outlying Islands (the)"),
        "us": ("us", "United States of America (the)"),
        "uy": ("com.uy", "Uruguay"),
        "uz": ("co.uz", "Uzbekistan"),
        "va": (None, "Holy See (the)"),
        "vc": ("com.vc", "Saint Vincent and the Grenadines"),
        "ve": ("co.ve", "Venezuela (Bolivarian Republic of)"),
        "vg": (None, "Virgin Islands (British)"),
        "vi": ("co.vi", "Virgin Islands (U.S.)"),
        "vn": ("com.vn", "Viet Nam"),
        "vu": ("vu", "Vanuatu"),
        "wf": (None, "Wallis and Futuna"),
        "ws": ("ws", "Samoa"),
        "ye": (None, "Yemen"),
        "yt": (None, "Mayotte"),
        "za": ("co.za", "South Africa"),
        "zm": ("co.zm", "Zambia"),
        "zw": ("co.zw", "Zimbabwe")
    }

    """
        The lang_variants table returns the different country codes that support 
        a given language. The country codes are 3166-1 two letter codes and the
        language codes are ISO 639-1. Derived from what a Linux system supports, by
        default. 
    """

    lang_variants: Dict[str, List[str]] = {
        'bn': ['bd', 'in'],
        'bo': ['cn', 'in'],
        'br': ['fr'],
        'bs': ['ba'],
        'ca': ['ad', 'es', 'fr', 'it'],
        'ce': ['ru'],
        'cs': ['cz'],
        'cv': ['ru'],
        'cy': ['gb'],
        'da': ['dk'],
        'de': ['at', 'be', 'ch', 'de', 'it', 'li', 'lu'],
        'dv': ['mv'],
        'dz': ['bt'],
        'el': ['cy', 'gr'],
        'en': ['ag', 'au', 'bw', 'ca', 'dk', 'gb', 'hk', 'ie', 'il', 'in', 'ng', 'nz', 'ph', 'sc', 'sg', 'us', 'za', 'zm', 'zw'],
        'eo': ['us'],
        'es': ['ar', 'bo', 'cl', 'co', 'cr', 'cu', 'do', 'ec', 'es', 'gt', 'hn', 'mx', 'ni', 'pa', 'pe', 'pr', 'py', 'sv', 'us', 'uy', 've'],
        'et': ['ee'],
        'eu': ['es', 'fr'],
        'fa': ['ir'],
        'ff': ['sn'],
        'fi': ['fi'],
        'fo': ['fo'],
        'fr': ['be', 'ca', 'ch', 'fr', 'lu'],
        'fy': ['de', 'nl'],
        'ga': ['ie'],
        'gd': ['gb'],
        'gl': ['es'],
        'gu': ['in'],
        'gv': ['gb'],
        'ha': ['ng'],
        'he': ['il'],
        'hi': ['in'],
        'hr': ['hr'],
        'ht': ['ht'],
        'hu': ['hu'],
        'hy': ['am'],
        'ia': ['fr'],
        'id': ['id'],
        'ig': ['ng'],
        'ik': ['ca'],
        'is': ['is'],
        'it': ['ch', 'it'],
        'iu': ['ca'],
        'ja': ['jp'],
        'ka': ['ge'],
        'kk': ['kz'],
        'kl': ['gl'],
        'km': ['kh'],
        'kn': ['in'],
        'ko': ['kr'],
        'ks': ['in'],
        'ku': ['tr'],
        'kw': ['gb'],
        'ky': ['kg'],
        'lb': ['lu'],
        'lg': ['ug'],
        'li': ['be', 'nl'],
        'ln': ['cd'],
        'lo': ['la'],
        'lt': ['lt'],
        'lv': ['lv'],
        'mg': ['mg'],
        'mi': ['nz'],
        'mk': ['mk'],
        'ml': ['in'],
        'mn': ['mn'],
        'mr': ['in'],
        'ms': ['my'],
        'mt': ['mt'],
        'my': ['mm'],
        'nb': ['no'],
        'ne': ['np'],
        'nl': ['aw', 'be', 'nl'],
        'nn': ['no'],
        'nr': ['za'],
        'oc': ['fr'],
        'om': ['et', 'ke'],
        'or': ['in'],
        'os': ['ru'],
        'pa': ['in', 'pk'],
        'pl': ['pl'],
        'ps': ['af'],
        'pt': ['br', 'pt'],
        'ro': ['ro'],
        'ru': ['ru', 'ua'],
        'rw': ['rw'],
        'sa': ['in'],
        'sc': ['it'],
        'sd': ['in', 'pk'],
        'se': ['no'],
        'si': ['lk'],
        'sk': ['sk'],
        'sl': ['si'],
        'sm': ['ws'],
        'so': ['dj', 'et', 'ke', 'so'],
        'sq': ['al', 'mk'],
        'sr': ['me', 'rs'],
        'ss': ['za'],
        'st': ['za'],
        'sv': ['fi', 'se'],
        'sw': ['ke', 'tz'],
        'ta': ['in', 'lk'],
        'te': ['in'],
        'tg': ['tj'],
        'th': ['th'],
        'ti': ['er', 'et'],
        'tk': ['tm'],
        'tl': ['ph'],
        'tn': ['za'],
        'to': ['to'],
        'tr': ['cy', 'tr'],
        'ts': ['za'],
        'tt': ['ru'],
        'ug': ['cn'],
        'uk': ['ua'],
        'ur': ['in', 'pk'],
        'uz': ['uz'],
        've': ['za'],
        'vi': ['vn'],
        'wa': ['be'],
        'wo': ['sn'],
        'xh': ['za'],
        'yi': ['us'],
        'yo': ['ng'],
        'zh': ['cn', 'hk', 'sg', 'tw'],
        'zu': ['za']}

    @classmethod
    def get_locales(cls) -> Dict[str, str]:
        locales: Dict[str, str] = {}
        country_code: str
        lang_code: str
        for lang_code in cls.lang_variants.keys():
            country_codes: List[str]
            country_codes = cls.lang_variants[lang_code]
            for country_code in country_codes:
                locale: str = f'{lang_code}-{country_code}'
                description: str = ''
                locales[locale] = description

        return locales
